# Based on
# http://conda.pydata.org/docs/travis.html
# https://github.com/xray/xray/blob/master/.travis.yml
# https://github.com/scipy/scipy/blob/master/.travis.yml

language: python
sudo: false # if false, use TravisCI's container based build

matrix:
    include:
    - python: 2.7
      env: CONDA_ENV=py27-min
    - python: 2.7
      env: CONDA_ENV=py27
    - python: 3.4
      env: CONDA_ENV=py34
    - python: 3.5
      env: CONDA_ENV=py35

addons:
    apt:
        packages:
            - ccache

cache:
#    - pip
    - ccache

# setup miniconda for numpy, scipy, pandas
before_install:
    - echo "before install"
    - export PATH=/usr/lib/ccache:$PATH
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-3.16.0-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - echo "install"
    - conda env create --file ci/requirements-$CONDA_ENV.yml
    - source activate test_env # all envs are named test_env in the yml files
    # needed to make sure that pandas is compiled against the right
    # version of numpy
    - if [[ "$CONDA_ENV" == "py27-min" ]]; then
        pip uninstall numpy --yes;
        pip uninstall pandas --yes;
        pip install --no-cache-dir numpy==1.9.0;
        pip install --no-cache-dir pandas==0.14.0;
      fi
    - conda list
    - echo $PATH
    - ls -l /home/travis/miniconda/envs/test_env/lib
    #- pip install . # use pip to automatically install anything not in the yml files (i.e. numpy/scipy/pandas for py3*)
    #- pip install scipy # won't do anything if already installed
    - pip install -e .

script:
    - py.test pvlib --cov=pvlib --cov-report term-missing

after_success:
    coveralls
