# CI on Windows via appveyor
# This file is based on MetPy's appveyor.yml

environment:

  CONDA_PATH: "C:\\Miniconda"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.6"

platform:
    - x86
    - x64

install:
    # Use the pre-installed Miniconda for the desired arch
    - ps: if($env:PYTHON_VERSION -eq '3.5')
            { $env:CONDA_PATH="$($env:CONDA_PATH)35" }
    - ps: if($env:PYTHON_VERSION -eq '3.6')
            { $env:CONDA_PATH="$($env:CONDA_PATH)36" }
    - ps: if($env:TARGET_ARCH -eq 'x64')
            { $env:CONDA_PATH="$($env:CONDA_PATH)-x64" }
    - ps: $env:path="$($env:CONDA_PATH);$($env:CONDA_PATH)\Scripts;$($env:CONDA_PATH)\Library\bin;C:\cygwin\bin;$($env:PATH)"
    - cmd: conda config --set always_yes yes --set changeps1 no
    - cmd: conda update -q conda
    # Useful for debugging any issues with conda
    - cmd: conda info -a

    # install depenencies
    - cmd: conda create -n test_env --yes --quiet python=%PYTHON_VERSION% pip numpy scipy tables pandas nose pytest pytz ephem numba siphon -c conda-forge
    - cmd: activate test_env
    - cmd: python --version
    - cmd: conda list

    # install pvlib
    - cmd: pip install -e .

build: false

test_script:
    - cmd: py.test -v pvlib
