name: pvlibdocs
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - numpy=1.14.2
    - scipy
    - pytables
    - pandas=0.22.0
    - pytz
    - ephem
    - numba
    - ipython=6.3
    - matplotlib=2.2.2
    - siphon=0.7.0
    - sphinx=1.7.2
    - netCDF4=1.3.1
    - hdf4=4.2.12
    - sphinx_rtd_theme
