name: pvlibdocs
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.5
    - mock  # needed for local python 2.7 builds
    - numpy=1.11.2
    - scipy
    - pandas=0.19.1
    - pytz
    - ephem
    - numba
    - ipython=5.2.2
    - ipywidgets
    - numpydoc
    - matplotlib=2.0.0
    - seaborn=0.7.1
    - siphon=0.4.0
    - sphinx=1.5
    - netCDF4=1.2.5
    - hdf4=4.2.12
    - sphinx_rtd_theme
    - docutils
    - nbsphinx
