name: pvlib
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2.7
    - numpy
    - scipy
    - pandas
    - pytz
    - ephem
    - numba
    - ipython=4.0.1
    - sphinx
    - numpydoc
    - matplotlib
    - seaborn
    - siphon
