name: pvlibdocs
dependencies:
    - python=3.5
    - mock  # needed for local python 2.7 builds
    - numpy
    - scipy
    - pandas
    - pytz
    - ephem
    - numba
    - ipython  #=4.0.1
    - ipywidgets
    - numpydoc
    - matplotlib
    - seaborn
    - sphinx  #=1.3.5  # same versions as rtd
    - sphinx_rtd_theme  #=0.1.7
    - docutils  #=0.12
