name: Welcome First-Time Contributor

on:
  pull_request_target:
    types: opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4
        with:
          pr-opened-msg: |
            ### Hey @{fc-author}! :tada:

            Thanks for opening your first pull request! We appreciate your
            contribution. Please ensure you have reviewed and understood the
            [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing/index.html).
            
            If AI is used for any portion of this PR, you must vet the content
            for technical accuracy.
